### ISSUE TITLE
Getting java.lang.UnsatisfiedLinkError even if the libaerofs.jar is in java.library.path

### ISSUE THREAD

**Issue by GRpro** [aerofs/jnotify#6]
I am getting the following error when trying to use you library:

Exception in thread "main" java.lang.UnsatisfiedLinkError: net.contentobjects.jnotify.linux.JNotify_linux.nativeInit()I
	at net.contentobjects.jnotify.linux.JNotify_linux.nativeInit(Native Method)
	at net.contentobjects.jnotify.linux.JNotify_linux.<clinit>(JNotify_linux.java:47)

Do you know how make this solved?
Thanks,

**Comment by huguesb** [comment]
The native libraries are *not* packaged inside the jar. They need to be build separately for each platform.

Once you have built the appropriate native library, you then need to manually load it using for instance [System.loadLibrary](https://docs.oracle.com/javase/7/docs/api/java/lang/System.html#loadLibrary(java.lang.String))

The jnotify jar doesn't do it because we've found that reliable loading takes some effort on Windows. Specifically we're using the full absolute path to the native library, which cannot be made to work inside the jar itself.
